from azure.eventhub import EventHubProducerClient, EventData
import app_config

connection_str = app_config.EVENT_HUB_CONNECTION

github_events_producer = EventHubProducerClient.from_connection_string(conn_str=connection_str, eventhub_name=app_config.EVENT_HUB_GITHUB)
github_import_producer = EventHubProducerClient.from_connection_string(conn_str=connection_str, eventhub_name=app_config.EVENT_HUB_GITHUB_IMPORT)
